name: Custom Zed Build (Linux)

on:
  workflow_dispatch: # دکمه Run workflow را در تب Actions فعال می‌کند

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
  CARGO_INCREMENTAL: 0
  CC: clang
  CXX: clang++

jobs:
  build-linux-x86:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linux Dependencies
        run: ./script/linux

      - name: Download WASI SDK
        run: ./script/download-wasi-sdk

      - name: Build Linux Bundle
        run: ./script/bundle-linux

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-linux-x86_64
          path: target/release/zed-linux-x86_64.tar.gz
